use_frameworks!

platform :ios, '8.0'

target 'AMKPopupView_Example' do
  pod 'AMKPopupView/AMKPopupView', :path => '../'
  pod 'AMKPopupView/AMKPopupViewPriority', :path => '../'
  pod 'AMKPopupView/AMKActionSheet', :path => '../'
  pod 'Masonry'
  pod 'YYWebImage'
end
